# ~/.config/starship.toml

# format="$directory$all$character"
# right_format="$all"
# Replace the "❯" symbol in the prompt with "➜"
# command_timeout = 50
# scan_timeout = 10

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$julia\
$nodejs\
$python\
$rlang\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$conda\
$character"""


[character]
success_symbol = "[\u25B6](bold green)"
error_symbol = "[\u25B6](bold red)"


[package]
disabled = true


[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"
discharging_symbol = " "

